# Generated by Django 5.1.3 on 2024-12-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_joint', models.DecimalField(decimal_places=2, max_digits=5)),
                ('second_joint', models.DecimalField(decimal_places=2, max_digits=5)),
                ('third_joint', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fourth_joint', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fifth_joint', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sixth_joint', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
